config/routes.rb
Rails.application.routes.draw do
  resources :books, only: [:index, :show]
  resources :authors, only: [:index, :show] do
    resources :books, only: [:index]
  end
  resources :users, only: [:new, :create, :edit, :update, :show]
  resource :session, only: [:new, :create, :destroy]
  root "books#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :ratings

  def average_rating
    rating_sum/ratings.size
  end

  def rating_sum
    self.ratings.map {|rating| rating.stars}.reduce(:+)
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ratings
  validates :email, uniqueness: true
  validates :password, presence: true

def password=(unhashed_password)
  @_password = BCrypt::Password.create(unhashed_password)
  self.password_hash = @_password
end

def password
  @_password ||= BCrypt::Password.new(password_hash)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  
  def current_user
     User.find_by(id: session["current_user_id"])
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params["id"])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.password == params[:password]
      session["current_user_id"] = @user.id
      redirect_to shares_path
    else
      @message = "You username or password was not correct"
      render :new
    end
  end

  def destroy
    session.delete("current_user_id")
    redirect_to shares_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to books_path
      session["current_user_id"] = @user.id
    else
      render :new
    end
  end

  def show
  end

  def user_params
    params.require(:user).permit(:nick_name, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/books/index.html.erb
<h1>Browse the Library</h1>
<ul>
  <% @books.each do |book| %>
    <li class="list-unstyled">
      <h3><%= link_to book.title, book_path(book.id)%></h3>
      <p>
        by <%= book.author.full_name %>
      </p>
      <p>
        <%= book.genre %>
      </p>
    </li>
  <% end %>
</ul>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p>
  <%= @book.author.full_name %>
</p>
<p>
  <%= '%.1f' % @book.rating_sum %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatToRead</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <%= link_to "literate", books_path, class: "navbar-brand" %>
        <header id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "Books", books_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if current_user %>
                <%= link_to "Logout", session_path, method: :delete %>
              <% else %>
                <%= link_to "Login", new_session_path %>
              <% end %>
            </li>
            <li>
              <%= link_to "#{current_user.nick_name}", user_path(current_user.id) if current_user %>
            </li>
            <li>
              <%= link_to "Sign up", new_user_path unless current_user %>
            </li>
          </ul>
        </header>
      </div>
    </nav>

    <div class="container-fluid">
      <% if @message %>
        <div class="alert alert-danger"><%= @message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :nick_name %>
    <%= f.text_field :nick_name, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<h1>Create an account</h1>

<% @user.errors.full_messages.each do |message| %>
    <div class="alert alert-danger"><%= message %></div>
<% end %>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :nick_name %>
    <%= f.text_field :nick_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<h1><%= current_user.nick_name %>'s Profile</h1>
<dl class="dl-horizontal">
  <dt>
    Nick name
  </dt>
  <dd>
    <%= current_user.nick_name %>
  </dd>
  <dt>
    Email
  </dt>
  <dd>
    <%= current_user.email %>
  </dd>
</dl>
<div class="profile-nav">
  <ul>
    <li class="list-unstyled">
      <%= link_to "Edit Account Info", edit_user_path(current_user.id) %>
    </li>
  </ul>
</div>